<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <!--START - Enable Compiler-Generated Code-->
    <PropertyGroup>
        <OutputPath>build\binaries\</OutputPath> <!--Executable Is Here, SKSSL Accomodates 1 Level Above-->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
    <Target Name="CleanBuildFolder" BeforeTargets="BeforeBuild">
        <RemoveDir Directories="build" Condition="Exists(build)"/>
    </Target>
    <ItemGroup>
        <ProjectReference Include="..\SKSSL.Generator\SKSSL.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\SKSSL\SKSSL.Engine.csproj"/>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
        <None Include="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>
    <ItemGroup>
        <!--      <Content Include="prototypes\**\*.*">
                  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                  <Link>..\prototypes\%(RecursiveDir)%(Filename)%(Extension)</Link>
              </Content>
              <Content Include="textures\**\*.*">
                  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                  <Link>..\textures\%(RecursiveDir)%(Filename)%(Extension)</Link>
              </Content>-->
        <Content Include="localization\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>..\localization\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
        <None Remove="ARIAL.TTF" />
        <Content Include="ARIAL.TTF">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <!--      <Content Include="settings.yaml"> 
                  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                  <Link>..\settings.yaml</Link>
              </Content>-->
    </ItemGroup>
    <!-- END - Enable Compiler-Generated Code -->

    <PropertyGroup>
        <TestingPlatformDotNetTestSupport>true</TestingPlatformDotNetTestSupport>
        <UseVSTest>true</UseVSTest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Clipper2" Version="2.0.0" />
        <PackageReference Include="Fluent.Net" Version="1.0.63"/>
        <PackageReference Include="FontStashSharp.Base" Version="1.2.9" />
        <PackageReference Include="FontStashSharp.MonoGame" Version="1.6.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
        <PackageReference Include="JetBrains.Profiler.Api" Version="1.4.13" />
        <PackageReference Include="LibVLCSharp" Version="3.10.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0"/>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.6" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.1.0"/>
        <PackageReference Include="MSTest.TestFramework" Version="4.1.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="Tomlyn" Version="2.4.1"/>
        <PackageReference Include="YamlDotNet" Version="18.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="GG_Map.png" />
      <EmbeddedResource Include="GG_Map.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="PLAIN_ROUND.png" />
      <EmbeddedResource Include="PLAIN_ROUND.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="GG_Borders.png" />
      <EmbeddedResource Include="GG_Borders.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>
</Project>