<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!--Enable Compiler-Generated Code-->
  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <!--Cleanup Compiler-Generated Code-->
  <Target Name="CleanSKSSLGeneratedFiles" BeforeTargets="BeforeBuild;BeforeRebuild">
    <Delete Files="@(CompilerGeneratedFilesToDelete)" />

    <ItemGroup>
      <CompilerGeneratedFilesToDelete Include="$(CompilerGeneratedFilesOutputPath)\SKSSL\*.g.cs" />
    </ItemGroup>

    <Delete Files="@(CompilerGeneratedFilesToDelete)" />
  </Target>
  
  <ItemGroup>
    <PackageReference Include="Fluent.Net" Version="1.0.63" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SKSSL.Generator\SKSSL.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
    <ProjectReference Include="..\SKSSL\SKSSL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Localization\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
</Project>