using System;
using System.Reflection;
using SKSSL.ECS;
using SKSSL.YAML;
using VYaml.Annotations;

namespace SKSSL.Extensions;

public static class ComponentYamlExtensions
{
    private const BindingFlags FieldFlags = BindingFlags.Public |
                                            BindingFlags.NonPublic |
                                            BindingFlags.Instance |
                                            BindingFlags.IgnoreCase;

    /// Converts Component to yaml object for serialization.
    public static YamlComponent ToYaml(Component component)
    {
        var result = new YamlComponent
        {
            Type = ComponentTypeHelper.NormalizeTypeName(component.GetType().Name)
        };

        Type type = component.GetType();

        // Serialize flags
        var map = result.Entries;
        map.Clear();

        foreach (FieldInfo field in type.GetFields(FieldFlags))
        {
            // If the yaml thing is supposed to ignore it, then so shall I.
            if (field.IsDefined(typeof(YamlIgnoreAttribute), true))
                continue;

            string key = field.Name.TrimStart('_');
            if (string.IsNullOrWhiteSpace(key))
                continue;
            
            // Filter out compiler-generated data.
            if (field.IsDefined(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true))
                continue;

            // Filter out backing-fields for {get;set;} properties.
            if (field.Name.Contains("k__BackingField"))
                continue;

            if (map.ContainsKey(key))
                continue;

            var value = field.GetValue(component);
            if (value is null)
                continue;

            map[key] = value;
        }

        // Serialize properties
        foreach (PropertyInfo prop in type.GetProperties(FieldFlags))
        {
            // Can't read it? Can't parse it.
            if (!prop.CanRead)
                continue;

            // Yaml system ignores it? So shall I.
            if (prop.IsDefined(typeof(YamlIgnoreAttribute), true))
                continue;

            // Ignore the equality contract generated by the record object type.
            if (prop.Name == "EqualityContract")
                continue;

            string key = prop.Name;

            if (map.ContainsKey(key))
                continue;

            var value = prop.GetValue(component);
            if (value is null)
                continue;

            map[key] = value;
        }

        return result;
    }

    /// Converts yaml component object to actual component object instance. This instance is NOT registered in the
    /// registry, and has no assigned entity due to this.
    /// <seealso cref="ComponentRegistry"/>
    public static Component FromYaml(YamlComponent yaml)
    {
        string typeName = ComponentTypeHelper.NormalizeTypeName(yaml.Type);
        if (!ComponentRegistry.TryGetComponentType(typeName, out Type? componentType))
            throw new Exception($"Failed to retrieve component type {yaml.Type} from registry.");

        Component? instance = ComponentRegistry.FastCreate(componentType!);

        if (instance is null)
            throw new Exception($"Type {componentType!.Name} is not a Component from {nameof(FromYaml)} call.");

        // For every yaml entry, deserialize as a field or a property, whichever works.
        foreach (var yamlField in yaml.Entries)
        {
            // Handle fields.
            FieldInfo? field = componentType!.GetField(yamlField.Key, FieldFlags);
            if (field != null)
            {
                object? value = YamlStringToValue(yamlField.Value, field.FieldType);
                field.SetValue(instance, value);
                continue;
            }

            // Handle properties.
            PropertyInfo? prop = componentType.GetProperty(yamlField.Key, FieldFlags);
            if (prop != null && prop.CanWrite)
            {
                object? value = YamlStringToValue(yamlField.Value, prop.PropertyType);
                prop.SetValue(instance, value);
            }
        }

        return instance;
    }

    // ReSharper disable once ConvertIfStatementToReturnStatement
    private static object? YamlStringToValue(object? value, Type targetType)
    {
        if (value == null)
            return null;

        if (targetType.IsInstanceOfType(value))
            return value;

        if (targetType.IsEnum)
            return Enum.Parse(targetType, value.ToString()!, true);

        return Convert.ChangeType(value, targetType);
    }

    /// Converts any value to a reasonable YAML-compatible string representation.
    /// Handles null, primitives, strings, Vectors, common MonoGame types, etc.
    public static string ValueToYamlString(object value)
    {
        Type type = value.GetType();

        // String: quote it
        if (type == typeof(string))
            return $"\"{value}\"";

        // Common MonoGame types
        if (type == typeof(Microsoft.Xna.Framework.Vector2))
        {
            var v = (Microsoft.Xna.Framework.Vector2)value;
            return $"{v.X}, {v.Y}";
        }

        if (type == typeof(Microsoft.Xna.Framework.Vector3))
        {
            var v = (Microsoft.Xna.Framework.Vector3)value;
            return $"{v.X}, {v.Y}, {v.Z}";
        }

        if (type == typeof(Microsoft.Xna.Framework.Color))
        {
            var c = (Microsoft.Xna.Framework.Color)value;
            return c.PackedValue.ToString("X8"); // or use Name if known
        }

        // Enums: use name
        if (type.IsEnum)
            return value.ToString()!;

        // Primitives: just ToString()
        if (type.IsPrimitive || type == typeof(decimal))
            return value.ToString()!.ToLowerInvariant(); // e.g., true/false instead of True/False

        // Fallback: ToString(), or type name if not helpful
        string str = value.ToString()!;
        return str != type.ToString() ? str : $"~{type.Name}"; // mark complex objects
    }
}