using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Reflection;
using SKSSL.ECS;
using SKSSL.YAML;
using YamlDotNet.Serialization;
using static System.StringComparison;

namespace SKSSL.Extensions;

public static class YamlCompExtensions
{
    public static ComponentYaml Clone(this ComponentYaml source)
        => new() { Type = source.Type, Entries = new Dictionary<string, object?>(source.Entries) };

    private const BindingFlags FieldFlags = BindingFlags.Public |
                                            BindingFlags.NonPublic |
                                            BindingFlags.Instance |
                                            BindingFlags.IgnoreCase;

    /// Converts Component to yaml object for serialization.
    [Pure]
    public static ComponentYaml ToYaml(this Component component)
    {
        var result = new ComponentYaml
        {
            Type = NormalizeTypeName(component.GetType().Name)
        };

        Type type = component.GetType();

        // Serialize flags
        var map = result.Entries;
        map.Clear();

        foreach (FieldInfo field in type.GetFields(FieldFlags))
        {
            // If the yaml thing is supposed to ignore it, then so shall I.
            if (field.IsDefined(typeof(YamlIgnoreAttribute), true))
                continue;

            string key = field.Name.TrimStart('_');
            if (string.IsNullOrWhiteSpace(key))
                continue;

            // Filter out compiler-generated data.
            if (field.IsDefined(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true))
                continue;

            // Filter out backing-fields for {get;set;} properties.
            if (field.Name.Contains("k__BackingField"))
                continue;

            if (map.ContainsKey(key))
                continue;

            var value = field.GetValue(component);
            if (value is null)
                continue;

            map[key] = value;
        }

        // Serialize properties
        foreach (PropertyInfo prop in type.GetProperties(FieldFlags))
        {
            // Can't read it? Can't parse it.
            if (!prop.CanRead)
                continue;

            // Yaml system ignores it? So shall I.
            if (prop.IsDefined(typeof(YamlIgnoreAttribute), true))
                continue;

            // Ignore the equality contract generated by the record object type.
            if (prop.Name == "EqualityContract")
                continue;

            string key = prop.Name;

            if (map.ContainsKey(key))
                continue;

            var value = prop.GetValue(component);
            if (value is null)
                continue;

            map[key] = value;
        }

        return result;
    }

    /// Converts yaml component object to actual component object instance. This instance is NOT registered in the
    /// registry, and has no assigned entity due to this.
    /// <seealso cref="ComponentRegistry"/>
    [Pure]
    public static Component FromYaml(this ComponentYaml yaml)
    {
        string typeName = NormalizeTypeName(yaml.Type);
        if (!ComponentRegistry.TryGetComponentType(typeName, out Type? componentType))
            throw new Exception($"Failed to retrieve component type {yaml.Type} from registry.");

        Component? instance = ComponentRegistry.FastCreate(componentType);

        if (instance is null)
            throw new Exception($"Type {componentType.Name} is not a Component from {nameof(FromYaml)} call.");

        // For every yaml entry, deserialize as a field or a property, whichever works.
        foreach (var yamlField in yaml.Entries)
        {
            // Handle fields.
            FieldInfo? field = componentType.GetField(yamlField.Key, FieldFlags);
            if (field != null)
            {
                object? value = YamlStringToValue(yamlField.Value, field.FieldType);
                field.SetValue(instance, value);
                continue;
            }

            // Handle properties.
            PropertyInfo? prop = componentType.GetProperty(yamlField.Key, FieldFlags);
            if (prop != null && prop.CanWrite)
            {
                object? value = YamlStringToValue(yamlField.Value, prop.PropertyType);
                prop.SetValue(instance, value);
            }
        }

        return instance;
    }

    // ReSharper disable once ConvertIfStatementToReturnStatement
    private static object? YamlStringToValue(object? value, Type targetType)
    {
        if (value == null)
            return null;

        if (targetType.IsInstanceOfType(value))
            return value;

        if (targetType.IsEnum)
            return Enum.Parse(targetType, value.ToString()!, true);

        return Convert.ChangeType(value, targetType);
    }
    
    /// <summary>
    /// Strips "Component" suffix for YAML tags (e.g. RenderableComponent → Renderable)
    /// </summary>
    public static string NormalizeTypeName(string typeName)
    {
        if (string.IsNullOrEmpty(typeName))
            return string.Empty;
        const string suffix = "Component";
        return typeName.EndsWith(suffix, OrdinalIgnoreCase) ? typeName[..^suffix.Length] : typeName;
    }
}