<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <NoWarn>$(NoWarn);SYSLIB0011;CS0108;CS8618;CS8619;NU5100</NoWarn>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SKSSL</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>SKSSL</PackageId>
        <Version>1.8.2</Version> <!--1.8.2 (Namespaces, Prototype / Entity Refactor)--> <!--Version Auto-Changed-->
        <Authors>LukeZurg22</Authors>
        <Description>Shared general game engine built on Monogame and GumUI.</Description>
        <PackageTags>logging, ecs, yaml, parsing</PackageTags>
        <RepositoryUrl>https://github.com/LukeZurg22/SKSSL</RepositoryUrl>
        <IncludeBuildOutput>true</IncludeBuildOutput> <!--For generated classes.-->

        <!--For Packaging-->
        <ExcludeTestAssets>true</ExcludeTestAssets>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateLibraryLayout>true</GenerateLibraryLayout>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <!--The Ones That Flow-->
        <PackageReference Include="FlatRedBall.GumCommon" Version="2026.5.31.1" PrivateAssets="none"/>
        <PackageReference Include="Gum.MonoGame" Version="2026.5.31.1" PrivateAssets="none"/>
        <PackageReference Include="MemoryPack" Version="1.21.4" PrivateAssets="none"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" PrivateAssets="none"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" PrivateAssets="none"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" PrivateAssets="none"/>
        <PackageReference Include="Myra" Version="1.6.1" PrivateAssets="none"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="RandN" Version="0.5.0" PrivateAssets="none"/>
        <PackageReference Include="Fluent.Net" Version="1.0.63" PrivateAssets="none"/>
        <PackageReference Include="ImGui.NET" Version="1.91.6.1" PrivateAssets="none"/>
        <PackageReference Include="ImGUI.NET.ToolBox" Version="0.1.1" PrivateAssets="none"/>
        <PackageReference Include="YamlDotNet" Version="18.0.0"/>

        <!--Private Ones-->
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All"/>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Testing.Platform" Version="1.7.3" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="17.14.1" PrivateAssets="all"/>
        <PackageReference Include="Tomlyn" Version="2.4.1"/>
    </ItemGroup>

    <!--Exclude Testhost Stuff-->
    <ItemGroup>
        <Content Update="testhost.exe;testhost*.exe;testhost*.dll;testhost*.json"
                 CopyToOutputDirectory="Never"
                 CopyToPublishDirectory="Never"/>
    </ItemGroup>

    <PropertyGroup>
        <!--<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>-->
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <!-- Ignore unwanted built-in generators -->
    <ItemGroup>
        <CompilerGeneratedFilesToExclude Include="**/*RegexGenerator*"/>
        <CompilerGeneratedFilesToExclude Include="**/*Regex.g.cs"/>
        <CompilerGeneratedFilesToExclude Include="**/*Yaml*"/>
        <CompilerGeneratedFilesToExclude Include="**/*VYaml*"/>
        <CompilerGeneratedFilesToExclude Include="**/*System*"/>
        <CompilerGeneratedFilesToExclude Include="**/*YAMLSerializer*"/>
        <CompilerGeneratedFilesToExclude Include="**/*BaseYaml*"/>
    </ItemGroup>

    <ItemGroup> <!--Reference to Source Generator(s)-->
        <ProjectReference Include="..\SKSSL.Generator\SKSSL.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <!-- Explicitly pack the generator DLL (adjust path if needed) -->
        <None Include="..\SKSSL.Generator\bin\$(Configuration)\netstandard2.0\SKSSL.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="true" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Networking\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Textures\TextureLoader.MaterialRegistry.cs">
            <DependentUpon>TextureLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="Textures\TextureLoader.HardcodedTextures.cs">
            <DependentUpon>TextureLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="Extensions\EntityExtensions_Clone.cs">
            <DependentUpon>EntityExtensions.cs</DependentUpon>
        </Compile>
        <Compile Update="Extensions\EntityExtensions_Components.cs">
            <DependentUpon>EntityExtensions.cs</DependentUpon>
        </Compile>
        <Compile Update="Extensions\EntityExtensions_Queries.cs">
            <DependentUpon>EntityExtensions.cs</DependentUpon>
        </Compile>
        <Compile Update="Textures\TextureLoader.IconRegistry.cs">
            <DependentUpon>TextureLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="Textures\TextureLoader.XNAContent.cs">
            <DependentUpon>TextureLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\ECSRegistries\ECSRegistry.Entity.cs">
            <DependentUpon>ECSRegistry.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\ECSRegistries\ECSRegistry.RawPrototype.cs">
            <DependentUpon>ECSRegistry.cs</DependentUpon>
        </Compile>
        <Compile Update="GameContentLoader\YamlLoader.cs">
            <DependentUpon>GameContentLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="GameContentLoader\ConsQJsonLoader.cs">
            <DependentUpon>GameContentLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="GameContentLoader\IYamlBlock.cs">
            <DependentUpon>YamlLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\ContentLoading\XNAContent.cs">
            <DependentUpon>TextureLoader.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\LoadPath.cs">
            <DependentUpon>GameSettings.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Data\ModifierOperator.cs">
          <DependentUpon>Modifier.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Data\ModifierStep.cs">
          <DependentUpon>Modifier.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\MeshComponent.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\SpriteComponents.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\Transform2DComponent.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\Transform3DComponent.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\AnimatedSpriteComponent.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Component\StatisticsComponent.cs">
          <DependentUpon>Component.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Entity\IDrawSystem.cs">
          <DependentUpon>EntitySystem.cs</DependentUpon>
        </Compile>
        <Compile Update="ECS\Entity\IUpdateSystem.cs">
          <DependentUpon>EntitySystem.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\Serializing\YamlBlock.cs">
          <DependentUpon>SerializerDefaultYaml.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\TextureLease.cs">
          <DependentUpon>TextureRegistry.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\TextureMap.cs">
          <DependentUpon>TextureRegistry.cs</DependentUpon>
        </Compile>
        <Compile Update="Meta\TextureType.cs">
          <DependentUpon>TextureRegistry.cs</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Assets\ConsoleFont.xnb" />
      <None Remove="Assets\icon.png" />
      <EmbeddedResource Include="Assets\icon.png" />
      <None Remove="Assets\icon.svg" />
      <EmbeddedResource Include="Assets\icon.svg" />
    </ItemGroup>

    <!-- START - !== ADD THE FOLLOWING TO INHERITING PROJECTS USING SKSSL AS AN ENGINE !== -->
    
    <!--<PropertyGroup>
        <OutputPath>build\binaries\</OutputPath> &lt;!&ndash;Executable Is Here, SKSSL Accomodates 1 Level Above&ndash;&gt;
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>
    <Target Name="CleanBuildFolder" BeforeTargets="BeforeBuild">
        <RemoveDir Directories="build" Condition="Exists(build)"/>
    </Target>
    <ItemGroup>
        <ProjectReference Include="..\SKSSL.Generator\SKSSL.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\SKSSL\SKSSL.Engine.csproj" />
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
        <None Include="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
    </ItemGroup>-->
    <!-- Add custom game folders here! (Below is an example for root-directory game files) -->
    <!--<ItemGroup>
        <Content Include="prototypes\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>..\prototypes\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
        <Content Include="textures\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>..\textures\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
        <Content Include="localization\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>..\localization\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </Content>
    </ItemGroup>-->

    <!--INCLUDE THESE IN YOUR .CSPROJ IF YOU WANT TO HAVE DEFAULTS-->
    <!--<ItemGroup>
        <Content Include="settings.yaml"> 
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>..\settings.yaml</Link>
    </Content>
    <Content Include="load_order.yaml"> 
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Link>..\load_order.yaml</Link>
    </Content>
    </ItemGroup>-->
    <!--END - Enabled Compiler-Generated Code!-->

</Project>
