using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

namespace SKSSL.Generator;

[Generator]
public class CommandGenerator : IIncrementalGenerator
{
    private const string CommandBaseName = "Command";
    private const string REG_NAME = "CommandRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations.
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => (RecordDeclarationSyntax)ctx.Node)
            .Where(static cls => cls.BaseList != null)
            .Collect();

        // Get compilation and combine.
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<RecordDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        INamedTypeSymbol? CommandSymbol
            = compilation.GetTypeByMetadataName(CommandBaseName) ?? FindInCompilation(compilation, CommandBaseName);

        if (CommandSymbol == null) return;

        var commands = new List<INamedTypeSymbol>();

        foreach (RecordDeclarationSyntax? classDecl in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
                continue;

            if (IsDerivedFrom(typeSymbol, CommandSymbol) && IsRelevantAssembly(typeSymbol.ContainingAssembly))
                commands.Add(typeSymbol);
        }

        if (commands.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(commands);
        spc.AddSource(REG_NAME, outputFile.ToString());
    }

    //@formatter:off
    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> commands)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace CommandRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class CommandRegistrar");
        sb.AppendLine("{");
        /*sb.AppendLine();
        sb.AppendLine("      [ModuleInitializer]");
        sb.AppendLine("      public static void Initialize()");
        sb.AppendLine("      {");
        sb.AppendLine("            // Wipe any pre-existing Command definitions.");
        //sb.AppendLine("            CommandRegistry.Clear();");
        //foreach (INamedTypeSymbol? proto in Commands)
        //{
        //    var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        //    var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        //    if (shortName.EndsWith("Command", StringComparison.OrdinalIgnoreCase))
        //        shortName = shortName[..^9];
        //    if (string.IsNullOrWhiteSpace(shortName)) continue;
        //    sb.AppendLine($"            CommandRegistry.GetOrRegister(\"{shortName}\", typeof({fullName}));");
        //}
        sb.AppendLine("      }");*/
        sb.AppendLine("}");
        
        return sb;
        //@formatter:on
    }

    
}