using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

namespace SKSSL.Generator;

[Generator]
public class CommandGenerator : IIncrementalGenerator
{
    private const string RegisterAttributeName = "RegisterCommand";
    private const string PROTO_REG_NAME = "CommandRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations that have attributes
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        // Resolve the attribute symbol.
        INamedTypeSymbol? registerAttrSymbol =
            (compilation.GetTypeByMetadataName(RegisterAttributeName) ??
             compilation.GetTypeByMetadataName(RegisterAttributeName + "Attribute") ??
             FindInCompilation(compilation, RegisterAttributeName) ??
             // Fallback: search every assembly the compilation can see.
             FindInCompilation(compilation, RegisterAttributeName + "Attribute")) ??
            (FindTypeInCompilation(compilation, RegisterAttributeName)
             ?? FindTypeInCompilation(compilation, RegisterAttributeName + "Attribute"));

        if (registerAttrSymbol is null)
            return;

        var commands = new List<INamedTypeSymbol>();

        // Walk every type that is visible to this compilation.
        foreach (INamedTypeSymbol? type in GetAllTypes(compilation))
        {
            if (type.IsAbstract || type.TypeKind != TypeKind.Class)
                continue;

            bool hasAttribute = type.GetAttributes()
                .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, registerAttrSymbol));

            if (hasAttribute)
                commands.Add(type);
        }

        if (commands.Count == 0)
            return;

        if (commands.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(commands);
        spc.AddSource(PROTO_REG_NAME, outputFile.ToString());
    }

    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> commands)
    {
        //@formatter:off
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace CommandRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class CommandRegistrar");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    public static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Wipe any pre-existing.");
        sb.AppendLine("        SKSSL.Console.GameConsole.Commands.Clear();");
        foreach (INamedTypeSymbol proto in commands)
        {
            var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            if (string.IsNullOrWhiteSpace(shortName)) continue;
            //sb.AppendLine($"       SKSSL.Console.GameConsole.AddCommand(typeof({fullName}));");
            sb.AppendLine($"        SKSSL.Console.GameConsole.AddCommand(new {fullName}());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb;
        //@formatter:on
    }
}