using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

namespace SKSSL.Generator;

[Generator]
public class CommandGenerator : IIncrementalGenerator
{
    // WARN: DOES NOT WORK, YET! REASON BEING DUE TO REFLECTION SEARCHING FOR RECORDS. COMMANDS ARE NOT RECORDS, THEY ARE
    //  CLASSES (FOR NOW)
    private const string CommandBaseName = "Command";
    private const string REG_NAME = "CommandRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations.
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static cls => cls.BaseList != null)
            .Collect();

        // Get compilation and combine.
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        INamedTypeSymbol? CommandSymbol
            = compilation.GetTypeByMetadataName(CommandBaseName) ?? FindInCompilation(compilation, CommandBaseName);

        if (CommandSymbol == null) return;

        var commands = new List<INamedTypeSymbol>();

        foreach (ClassDeclarationSyntax? classDecl in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
                continue;

            if (IsDerivedFrom(typeSymbol, CommandSymbol) && IsRelevantAssembly(typeSymbol.ContainingAssembly))
                commands.Add(typeSymbol);
        }

        if (commands.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(commands);
        spc.AddSource(REG_NAME, outputFile.ToString());
    }

    //@formatter:off
    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> commands)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace CommandRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class CommandRegistrar");
        sb.AppendLine("{");
        /*sb.AppendLine();
        sb.AppendLine("      [ModuleInitializer]");
        sb.AppendLine("      public static void Initialize()");
        sb.AppendLine("      {");
        sb.AppendLine("            // Wipe any pre-existing Command definitions.");
        //sb.AppendLine("            CommandRegistry.Clear();");
        //foreach (INamedTypeSymbol? proto in Commands)
        //{
        //    var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        //    var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        //    if (shortName.EndsWith("Command", StringComparison.OrdinalIgnoreCase))
        //        shortName = shortName[..^9];
        //    if (string.IsNullOrWhiteSpace(shortName)) continue;
        //    sb.AppendLine($"            CommandRegistry.GetOrRegister(\"{shortName}\", typeof({fullName}));");
        //}
        sb.AppendLine("      }");*/
        sb.AppendLine("}");
        
/*
         // using SKSSL.Console;  USE THIS USING, THEN CALL THE FOLLOWING TO ADD A COMMAND       GameConsoleOptions.AddCommand();
         *        var inbuiltCommands = new IConsoleCommand[]
        {
            new ClearScreenCommand(consoleRenderer),
            new ExitCommand(game),
            new HelpCommand(),
        }.Concat(CommandFactory.CreateCommands()).ToArray();
        GameConsoleOptions.Commands.AddRange(inbuiltCommands);
         * 
         */
        
        return sb;
        //@formatter:on
    }
}