using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

namespace SKSSL.Generator;

[Generator]
public class ComponentGenerator : IIncrementalGenerator
{
    private const string ComponentBaseName = "Component";
    private const string PROTO_REG_NAME = "ComponentRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations.
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => (RecordDeclarationSyntax)ctx.Node)
            .Where(static cls => cls.BaseList != null)
            .Collect();

        // Get compilation and combine.
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<RecordDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        INamedTypeSymbol? ComponentSymbol
            = compilation.GetTypeByMetadataName(ComponentBaseName) ??
              FindInCompilation(compilation, ComponentBaseName);

        if (ComponentSymbol == null) return;

        var components = new List<INamedTypeSymbol>();

        foreach (RecordDeclarationSyntax? classDecl in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
                continue;

            if (IsDerivedFrom(typeSymbol, ComponentSymbol) && IsRelevantAssembly(typeSymbol.ContainingAssembly))
                components.Add(typeSymbol);
        }

        if (components.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(components);
        spc.AddSource(PROTO_REG_NAME, outputFile.ToString());
    }

    //@formatter:off
    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> components)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine("using VYaml.Annotations;");
        sb.AppendLine();
        sb.AppendLine("namespace ComponentRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class ComponentRegistrar");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("      [ModuleInitializer]");
        sb.AppendLine("      public static void Initialize()");
        sb.AppendLine("      {");
        sb.AppendLine("            // Wipe any pre-existing Component / entity definitions.");
        sb.AppendLine("            ComponentRegistry.Clear();");
        foreach (INamedTypeSymbol? proto in components)
        {
            var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            if (shortName.EndsWith("Component", StringComparison.OrdinalIgnoreCase))
                shortName = shortName[..^9];
            if (string.IsNullOrWhiteSpace(shortName)) continue;
            sb.AppendLine($"            ComponentRegistry.GetOrRegister(\"{shortName}\", typeof({fullName}));");
        }
        sb.AppendLine("      }");
        sb.AppendLine("}");
        
        /*sb.AppendLine();
        foreach (INamedTypeSymbol? proto in components)
        {
            var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            if (shortName.EndsWith("Component", StringComparison.OrdinalIgnoreCase))
                shortName = shortName[..^9];
            if (string.IsNullOrWhiteSpace(shortName)) continue;
            sb.AppendLine($"[YamlObjectUnion(\"!{shortName}\", typeof({fullName}))]");
        }
        sb.AppendLine("public partial record Component");
        sb.AppendLine("{");
        sb.AppendLine("public int Test {get; set;}=0;");
        sb.AppendLine("}");*/
        
        return sb;
        //@formatter:on
    }

   
}