using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SKSSL.Generator;

[Generator]
public class PrototypeGenerator : IIncrementalGenerator
{
    private const string PrototypeBaseName = "Prototype";
    private const string PROTO_REG_NAME = "PrototypeRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations.
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static cls => cls.BaseList != null)
            .Collect();

        // Get compilation and combine.
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        INamedTypeSymbol? prototypeSymbol
            = compilation.GetTypeByMetadataName(PrototypeBaseName) ?? FindPrototypeInCompilation(compilation);

        if (prototypeSymbol == null) return;

        var prototypes = new List<INamedTypeSymbol>();

        foreach (ClassDeclarationSyntax? classDecl in classes)
        {
            SemanticModel semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
                continue;

            if (IsDerivedFrom(typeSymbol, prototypeSymbol))
                prototypes.Add(typeSymbol);
        }

        if (prototypes.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(prototypes);
        spc.AddSource(PROTO_REG_NAME, outputFile.ToString());
    }

    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> prototypes)
    {
        //@formatter:off
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace PrototypeRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class PrototypeRegistrar");
        sb.AppendLine("{");
        //sb.AppendLine("     public static readonly Dictionary<string, Type> Prototypes = new();");
        sb.AppendLine();
        sb.AppendLine("      [ModuleInitializer]");
        sb.AppendLine("      public static void Initialize()");
        sb.AppendLine("      {");
        sb.AppendLine("            // Wipe any pre-existing prototype / entity definitions.");
        sb.AppendLine("            SKSSL.ECS.Registry.MasterRegistryManager.Clear();");
        // Accommodating base-entity type, which can exist out in the wild. Base-prototype, however, cannot!
        sb.AppendLine($"            SKSSL.ECS.Registry.MasterRegistryManager.RegisterTypeDefinition(\"Entity\", typeof(global::SKSSL.ECS.Entity));");
        foreach (INamedTypeSymbol? proto in prototypes)
        {
            var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            if (shortName.EndsWith("Prototype", StringComparison.OrdinalIgnoreCase))
                shortName = shortName[..^9];
            
            if (string.IsNullOrWhiteSpace(shortName)) continue;
            sb.AppendLine($"            SKSSL.ECS.Registry.MasterRegistryManager.RegisterTypeDefinition(\"{shortName}\", typeof({fullName}));");
        }
        sb.AppendLine("      }");
        sb.AppendLine("}");
        return sb;
        //@formatter:on
    }
    

    private static INamedTypeSymbol? FindPrototypeInCompilation(Compilation compilation)
    {
        // Fallback: search all types
        return compilation.GlobalNamespace
            .GetNamespaceMembers()
            .SelectMany(GetAllTypes)
            .FirstOrDefault(t => t.Name == PrototypeBaseName && !t.IsGenericType);
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (INamedTypeSymbol? type in ns.GetTypeMembers())
            yield return type;

        foreach (INamespaceSymbol? nestedNs in ns.GetNamespaceMembers())
        foreach (INamedTypeSymbol? type in GetAllTypes(nestedNs))
            yield return type;
    }

    private static bool IsDerivedFrom(ITypeSymbol type, ITypeSymbol baseType)
    {
        INamedTypeSymbol? current = type.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }

        return false;
    }
}