using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

namespace SKSSL.Generator;

[Generator]
public class PrototypeGenerator : IIncrementalGenerator
{
    private const string PrototypeBaseName = "Prototype";
    private const string PROTO_REG_NAME = "PrototypeRegistrar.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations.
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(static cls => cls.BaseList != null)
            .Collect();

        // Get compilation and combine.
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty) return;

        INamedTypeSymbol? prototypeSymbol
            = compilation.GetTypeByMetadataName(PrototypeBaseName) ??
              FindInCompilation(compilation, PrototypeBaseName);

        if (prototypeSymbol == null) return;

        var prototypes = new List<INamedTypeSymbol>();

        foreach (INamedTypeSymbol? classDecl in GetAllTypes(compilation))
        {
            if (classDecl is null || classDecl.IsAbstract)
                continue;

            if (classDecl.Name.Equals("Prototype", StringComparison.OrdinalIgnoreCase))
                continue;

            if (IsDerivedFrom(classDecl, prototypeSymbol))
                prototypes.Add(classDecl);
        }

        if (prototypes.Count == 0) return;

        StringBuilder outputFile = GenerateOutputFile(prototypes);
        spc.AddSource(PROTO_REG_NAME, outputFile.ToString());
    }

    private static StringBuilder GenerateOutputFile(List<INamedTypeSymbol> prototypes)
    {
        //@formatter:off
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace PrototypeRegistrar;");
        sb.AppendLine();
        sb.AppendLine("public static class PrototypeRegistrar");
        sb.AppendLine("{");
        //sb.AppendLine("     public static readonly Dictionary<string, Type> Prototypes = new();");
        sb.AppendLine();
        sb.AppendLine("      [ModuleInitializer]");
        sb.AppendLine("      public static void Initialize()");
        sb.AppendLine("      {");
        sb.AppendLine("            // Wipe any pre-existing prototype / entity definitions.");
        sb.AppendLine("            SKSSL.ECS.Registry.MasterRegistryManager.Clear();");
        foreach (INamedTypeSymbol? proto in prototypes)
        {
            var fullName = proto.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var shortName = proto.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            if (shortName.EndsWith("Prototype", StringComparison.OrdinalIgnoreCase))
                shortName = shortName[..^9];
            
            if (string.IsNullOrWhiteSpace(shortName)) continue;
            sb.AppendLine($"            SKSSL.ECS.Registry.MasterRegistryManager.RegisterTypeDefinition(\"{shortName}\", typeof({fullName}));");
        }
        sb.AppendLine("      }");
        sb.AppendLine("}");
        return sb;
        //@formatter:on
    }
}