using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

[Generator]
public class RegisteredSystemGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "SKSSL.ECS.RegisterSystemAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // NOTE: No need to generate the attribute again. As it turns out, it can just be referenced here.
        // Provide the attribute
        /*context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("RegisterSystemAttribute.g.cs", """
                // <auto-generated/>
                namespace SKSSL.ECS
                {
                    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                    public sealed class RegisterSystemAttribute : global::System.Attribute
                    {
                        public string? Name { get; }
                        public int Priority { get; } = 0;

                        public RegisterSystemAttribute() { }
                        public RegisterSystemAttribute(string name) => Name = name;
                    }
                }
                """);
        });*/

        // Find all classes with the attribute
        var systemsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSystemInfo(ctx))
            .Where(static info => info != null);

        // Generate the list
        context.RegisterSourceOutput(systemsProvider.Collect(), static (spc, systems) =>
        {
            if (systems.IsDefaultOrEmpty) return;

            var source = GenerateSystemList(systems!);
            spc.AddSource("SystemRegistry.g.cs", source);
        });
    }

    private static SystemInfo? GetSystemInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol || 
            symbol.IsAbstract || 
            symbol.InstanceConstructors.All(c => c.Parameters.Length > 0))
        {
            // Skip abstract classes or classes without parameterless constructor.
            return null;
        }

        AttributeData attr = ctx.Attributes[0];

        var name = attr.ConstructorArguments.Length > 0 
            ? attr.ConstructorArguments[0].Value as string 
            : symbol.Name;

        var priority = 0;
        // TODO: Add support for named arguments (Priority, etc.) if needed

        return new SystemInfo(
            FullTypeName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Name: name ?? symbol.Name,
            Order: priority
        );
    }

    private static string GenerateSystemList(ImmutableArray<SystemInfo> systems)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace SKSSL.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SystemRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly IReadOnlyList<EntitySystem> AllSystems = new EntitySystem[]");
        sb.AppendLine("    {");

        // Sort by priority
        foreach (SystemInfo? sys in systems.OrderBy(s => s.Order))
        {
            sb.AppendLine($"        new {sys.FullTypeName}(), // {sys.Name}");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

internal record SystemInfo(string FullTypeName, string Name, int Order);