using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SKSSL.Generator;

[Generator]
public class RegisteredSystemGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "SKSSL.ECS.RegisterSystemAttribute";
    private const string SYS_REG_NAME = "SystemRegistry.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with the attribute
        var systemsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSystemInfo(ctx))
            .Where(static info => info != null)
            .Collect();

        // Generate the list.
        context.RegisterSourceOutput(systemsProvider, (spc, list) =>
        {
            if (list.IsDefaultOrEmpty)
            {
                spc.AddSource(SYS_REG_NAME, "// No systems found");
                return;
            }

            spc.AddSource(SYS_REG_NAME, GenerateSystemList(list!));
        });
    }


    private static SystemInfo? GetSystemInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol ||
            symbol.IsAbstract ||
            symbol.InstanceConstructors.All(c => c.Parameters.Length > 0))
        {
            // Skip abstract classes or classes without parameterless constructor.
            return null;
        }

        AttributeData attr = ctx.Attributes[0];

        var name = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value as string
            : symbol.Name;

        var priority = 0;
        // TODO: Add support for named arguments (Priority, etc.) if needed

        return new SystemInfo(
            FullTypeName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Name: name ?? symbol.Name,
            Priority: priority
        );
    }

    private static string GenerateSystemList(ImmutableArray<SystemInfo> systems)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace SKSSL.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class SystemInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            SystemManager.Clear(); // Clean the list!");
        foreach (SystemInfo? sys in systems.OrderBy(s => s.Priority))
            sb.AppendLine($"            SystemManager.Register<{sys.FullTypeName}>(); // {sys.Name}");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

internal record SystemInfo(string FullTypeName, string Name, int Priority);