using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static SKSSL.Generator.SharedMethods;

// ReSharper disable BadControlBracesIndent

namespace SKSSL.Generator;

[Generator]
public class SystemGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "SKSSL.ECS.RegisterSystemAttribute";
    private const string SYS_REG_NAME = "SystemRegistry.g.cs";

    /*
     * There are no Entity Systems defined in SKSSL by default as of 20260804.
     * Why? Well, defining existing systems for specific entity types defeats the
     * purpose of a generic library, of course!
     */

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with the attribute
        var systemsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSystemInfo(ctx))
            .Where(static info => info != null)
            .Collect();

        // Generate the list.
        context.RegisterSourceOutput(systemsProvider, (spc, list) =>
        {
            if (list.IsDefaultOrEmpty)
            {
                spc.AddSource(SYS_REG_NAME, "// No systems found");
                return;
            }

            spc.AddSource(SYS_REG_NAME, GenerateSystemList(list!));
        });
    }

    private static string GenerateSystemList(ImmutableArray<SystemInfo> systems)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SKSSL.ECS;");
        sb.AppendLine();
        sb.AppendLine("namespace SKSSL.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class SystemInitializer");
        sb.AppendLine("{");
        sb.AppendLine("     [ModuleInitializer]");
        sb.AppendLine("     public static void Initialize()");
        sb.AppendLine("     {");
        sb.AppendLine("         SystemManager.Clear(); // Clean the list!");
        foreach (SystemInfo? sys in systems.OrderBy(s => s.Priority))
        {
            sb.AppendLine($"         SystemManager.Register<{sys.FullTypeName}>(); // {sys.Name}");
        }

        sb.AppendLine("     }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}